
num_layers: 5
width: 256
dataset: 'cifar10'
hparas:                                   
  epochs: 30
  lr: .001
  weight_decay: 0
  batch_size: 32
  momentum: None
experiment_hparas:
  num_magnitudes: 10
  magnitude_type: 'frobenius'
  optimizer: 'AdamW'
