
num_layers: 5
width: 256
dataset: 'cifar10'
hparas:                                   
  epochs: 30
  lr: .01
  weight_decay: 0.01
  batch_size: 512
experiment_hparas:
  num_magnitudes: 10
  magnitude_type: 'frobenius'
  optimizer: 'Muon'
